Reviwer_details/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "reviewer"

urlpatterns = [
    path("apply", views.profile, name="profile"),
    path('resume', views.stream_file, name='resume'),
    path('apply/submit', views.submit_form, name='submit_profile'),
]

capstone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('Reviwer_details.urls')),
    path('paper/', include('paper.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

paper/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'paper'

urlpatterns = [
    path('upload', views.paper, name='upload_paper'),
    path('<id>', views.paper_detail, name='paper_detail'),
    path('', views.papers, name='paper_list'),
    path("<int:pk>/report", views.stream_file, name="report_pdf"),
    path('<id>/<action>', views.update_paper, name="update_paper")
]

Reviwer_details/models.py
from django.db import models

# Create your models here.

Reviwer_details/views.py
from django.core.mail import mail_admins
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.contrib.auth import models
from django.urls import reverse
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.decorators import user_passes_test, login_required
from django.shortcuts import get_object_or_404
from authentication.models import ReviewerProfile

from authentication.utils import is_reviewer
from paper.models import Domain

User = auth.get_user_model()


@user_passes_test(is_reviewer)
@login_required
def profile(request: HttpRequest):
    rprofile: ReviewerProfile = request.user.reviewerprofile # type: ignore
    if rprofile.state == 'accepted':
        return redirect('paper:paper_list')
    if request.method == "POST":
        f_name = request.POST['fname']
        l_name = request.POST['lname']
        email = request.POST['email']

        profession = request.POST.get('profession')
        institute = request.POST.get('ins_name')
        qualification = request.POST.get('H_Q')
        domains = request.POST.getlist('domains')

        resume = request.FILES.get('resume')


        user: models.AbstractUser = request.user # type: ignore

        user.first_name = f_name
        user.last_name = l_name
        user.email = email

        updates = {
                'state': "draft",
                'profession': profession,
                'institute': institute,
                'qualification': qualification,
        }

        if resume:
            updates['resume'] = resume


        for key, val in updates.items():
            rprofile.__setattr__(key, val)
        rprofile.domains.set(Domain.objects.filter(short_name__in=domains))

        print(updates, rprofile.profession, rprofile.clean_fields())
        rprofile.save()
        user.save()
        return redirect('reviewer:profile')

    domains = Domain.objects.all()
    return render(request, "Reviwer_detail/Reviewer_detail.html", { 'me': request.user, 'rprofile': rprofile, 'domains': domains })

@login_required
def submit_form(request):
    if request.method == 'POST':
        # Process the form data
        # Send email
        rprofile = request.user.reviewerprofile #type: ignore
        rprofile.state = 'pending'
        rprofile.save()

        mail_admins(
            "Profile for review",
            f"Name: {request.user.first_name}\nEmail: {request.user.email}\nMessage: Hello, your details are pending for review."
        )

        messages.success(request, 'Details submitted successfully')

    # Render the form template for GET requests
    return redirect(reverse('authentication:profile'))


def stream_file(request):
    profile = get_object_or_404(ReviewerProfile, user=request.user)
    response = HttpResponse()

    response['Content-Type'] = "application/pdf"
    response['Content-Length'] = len(profile.resume)
    response.write(profile.resume.read())
    return response

templates/Reviwer_detail/Reviewer_detail.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reviewer Detail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</body>
</html>
</head>
<body>

    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>Message:</strong> {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}

    <h3>Fill up your details</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="fname">First Name</label>
            <input type="text" class="form-control" id="fname" name="fname" placeholder="Enter Your First Name" value="{{me.first_name}}">
        </div>
        <div class="form-group">
            <label for="lname">Last Name</label>
            <input type="text" class="form-control" id="lname" name="lname" placeholder="Enter Your Last Name" value="{{me.last_name}}">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter Your Email Address" value="{{me.email}}">
        </div>
        <div class="form-group">
            <label for="Profession">Profession:</label>
            <select class="form-control" name="profession" id="profession">
                <option value="" disabled selected>---</option>
                <option value="professor" {%if rprofile.profession == 'professor' %} selected {%endif%}>Professor</option>
                <option value="developer" {%if rprofile.profession == 'developer' %} selected {%endif%}>Developer</option>
              </select>
            </div>
        <div class="form-group">
            <label for="ins_name">Institue name:</label>
            <input value="{{ rprofile.institute }}" type="text" class="form-control" id="ins_name" name="ins_name" placeholder="Enter Institue name">
        </div>
        <div class="form-group">
            <label for="H_Q">Higher Qualification: </label>
            <input type="H_Q" class="form-control" id="H_Q" name="H_Q" placeholder="Enter Qualification" value="{{rprofile.qualification}}">
        </div>
        <div class="form-group">
            <label for="domain">Domain:</label>
            <select multiple class="form-control" name="domains" id="domains">
                {%for  domain in domains%}
                    <option value="{{domain.short_name}}" {% if domain in rprofile.domains.all %} selected {%endif%}>{{domain.name}}</option>
                {%endfor%}
            </select>
        </div>
        <div class="form-group">
            <label for="resume">Upload your Resume:</label></br>
            <input type="file" class="form-control" id="resume" name="resume" placeholder="Resume" value="{{rprofile.resume}}">
            {%if rprofile.resume%}
            Uploaded resume: <a href="{%url 'reviewer:resume'%}">{{rprofile.resume.name}}</a>
            {%endif%}
        </div>
        {%if rprofile.state == "draft" %}
        <button type="button" id="hide" class="btn btn-primary">Edit</button>
        <button id="save" type="submit" class="btn btn-primary" style="display: none;">Save Changes</button>
        {%endif%}
    </form>
    {% if rprofile.state == "draft" %}
    <form method="post" action="{%url 'reviewer:submit_profile'%}">
        {%csrf_token%}
        <button id="submit" type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% elif rprofile.state == "pending" %}
    <div class="message">Your profile is pending for review</div>
    {% elif rprofile.state == "accepted" %}
    <a href="{%url 'paper:paper_list' %}">Papers assigned</a>
    {%endif%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script>
        window.addEventListener('DOMContentLoaded', function() {
            const tags = document.querySelectorAll(".form-control");
            const hide = document.getElementById("hide");

            hide && hide.addEventListener("click", function () {
                const submit_button = document.getElementById("save");
                if (submit_button.style.display === "none") {
                    hide.innerHTML = "Cancel";
                    submit_button.style.display = "";
                    [...tags].map(t => {
                        t.removeAttribute('readonly')
                        t.removeAttribute('disabled')
                    })
                } else {
                    hide.innerHTML = "Edit";
                    submit_button.style.display = "none";
                    [...tags].map(t => {
                        t.setAttribute('readonly', '')
                        t.setAttribute('disabled', '')
                    })
                }
                return false;
            });

            [...tags].map(t => {
                t.setAttribute('readonly', '')
                t.setAttribute('disabled', '')
            })
        })
    </script>
</body>
</html>