capstone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('Reviwer_details.urls')),
    path('paper/', include('paper.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

paper/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'paper'

urlpatterns = [
    path('upload', views.paper, name='upload_paper'),
    path('<id>', views.paper_detail, name='paper_detail'),
    path('', views.papers, name='paper_list'),
    path("<int:pk>/report", views.stream_file, name="report_pdf"),
    path('<id>/<action>', views.update_paper, name="update_paper")
]

paper/models.py
from django.db import models
from django.conf import settings



class Domain(models.Model):
    short_name = models.CharField(max_length=20)
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)

    def __str__(self) -> str:
        return self.short_name


class Paper(models.Model):
    name = models.CharField(max_length=20,null=True)
    author_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    authors = models.TextField(null=True, blank=True)
    mentor = models.CharField(max_length=20,null=True)
    institute = models.CharField(max_length=20,null=True)
    paper = models.FileField(null=True, upload_to="papers")
    status=models.CharField(default="pending", max_length=20, choices=(
        ("pending", "pending"),
        ("approved", "approved"),
        ("rejected", "rejected")
    ))
    reviewer_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True, related_name="reviewer")
    domain = models.ForeignKey(Domain, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"Paper {self.pk} by {self.name}"

paper/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse, HttpRequest
from django.shortcuts import get_object_or_404, get_list_or_404
from django.urls import reverse
from authentication.utils import is_reviewer, get_reviewer_with_min_papers
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.conf import settings

from .models import Domain, Paper


def paper(request: HttpRequest):
    if request.method == "POST":
        Author_name = request.POST['Author_name']
        Co_author = request.POST['Co_author']
        Mname = request.POST['Mname']
        Institute = request.POST['Institute']
        domain = request.POST['domain']
        paper = request.FILES['paper']
        authors = [request.POST[f"co_author{i}"] for i in range(int(Co_author))]

        reviewer = get_reviewer_with_min_papers(domain)

        new_paper = Paper.objects.create(
            author_id=request.user,
            name=Author_name,
            authors = "\n".join(authors),
            mentor = Mname,
            institute = Institute,
            paper = paper,
            reviewer_id= reviewer,
            domain = Domain.objects.get(short_name=domain)
        )
        new_paper.save()

        reviewer.email_user("Kindly review the paper assigned to you..!", f"Paper with id {new_paper.pk} is assigned to you", settings.EMAIL_HOST_USER)

        return redirect(reverse('paper:paper_detail', args=[new_paper.pk]))
    return render(request, "authentication/upload_paper.html", { 'domains': Domain.objects.all() })

@login_required
def paper_detail(request, id):
    paper = get_object_or_404(Paper, pk=id)
    return render(request, 'paper/detail.html', {'paper': paper, 'is_reviewer': paper.reviewer_id == request.user})

@login_required
def papers(request):
    papers = []
    if is_reviewer(request.user):
        if request.user.reviewerprofile.state == 'pending':
            messages.error(request, 'Please complete your profile first')
            return redirect('reviewer:profile')

        papers = get_list_or_404(Paper, reviewer_id=request.user)
    else:
        papers = Paper.objects.filter(author_id=request.user.id)
    return render(request, "paper/all.html", { 'papers': papers })

@user_passes_test(is_reviewer)
def update_paper(request, id, action):
    paper = get_object_or_404(Paper, pk=id)

    paper.status = "approved" if action == "approve" else "rejected"


    paper.save()
    comment = request.POST.get("comment")
    paper.author_id.email_user("Status upadate on your paper..!", f"Paper with id {paper.pk} has been {paper.status}\n REASON: {comment}", settings.EMAIL_HOST_USER)

    return redirect("paper:paper_detail", id)

def stream_file(request, pk):
    paper = get_object_or_404(Paper, id=pk)
    response = HttpResponse()

    response['Content-Type'] = "application/pdf"
    response['Content-Length'] = len(paper.paper)
    response.write(paper.paper.read())
    return response

templates/paper/all.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/semantic-ui@2.5.0/dist/semantic.min.css"
    />
    <title>Papers</title>
    <style>
      .container {
        margin: 20px;
      }

      .menu {
        margin-bottom: 20px;
      }

      .segment {
        margin-bottom: 20px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="ui secondary menu">
        <a class="item active" href="index.html">Home</a>
        {% comment %}if user is not authenticated show sign up and sign in{% endcomment %}
        {% if not user.is_authenticated %}
        <a class="item" href="/signup">Sign Up</a>
        <a class="item" href="/signin">Sign In</a>
        {% endif %}
        <div class="right menu">
          {% if user.is_authenticated %}
          <div class="item">
            <a class="ui red button" href="/signout">Sign Out</a>
          </div>
          {% endif %}
        </div>
      </div>
      <h1 class="ui header">Papers</h1>

      {% for paper in papers %}
      <section class="ui raised segment">
        <h2 class="ui header">{{ paper.name }}</h2>
        <p>
          <strong>Status:</strong> {{ paper.status }}
        </p>
        <a class="ui primary button" href="/paper/{{ paper.id }}">View</a>
      </section>
      {% endfor %}
    </div>
  </body>
</html>

templates/paper/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.5.0/dist/semantic.min.css">
    <style>
        body {
            background-color: #f2f2f2;
            font-family: Arial, sans-serif;
            padding: 20px;
        }

        h1 {
            color: #2185d0;
            font-size: 24px;
            margin-bottom: 10px;
        }

        h2 {
            color: #2185d0;
            font-size: 20px;
            margin-bottom: 10px;
        }

        p {
            margin-bottom: 10px;
        }

        a {
            color: #2185d0;
            text-decoration: none;
        }

        form {
            margin-top: 20px;
        }

        input[type="text"] {
            margin-right: 10px;
        }

        button[type="submit"] {
            background-color: #2185d0;
            color: #ffffff;
            padding: 5px 10px;
            border: none;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="ui secondary menu">
            <a class="item active" href="/">Home</a>
            {% comment %}if user is not authenticated show sign up and sign in{% endcomment %}
            {% if not user.is_authenticated %}
                <a class="item" href="/signup">Sign Up</a>
                <a class="item" href="/signin">Sign In</a>
            {% endif %}
            <div class="right menu">
                <div class="item">
                    <button class="ui inverted blue button" type="conference"><a href="{% url 'paper:paper_list'  %}">Back to Paperlist</a></button>
                </div>
                {% if user.is_authenticated %}
                    <div class="item">
                        <a class="ui red button" href="/signout">Sign Out</a>
                    </div>
                {% endif %}
            </div>
        </div>

        {% if not is_reviewer %}
            <h1>Author name: {{ paper.name }}</h1>
            <h2>Mentor: {{ paper.mentor }}</h2>
        {% endif %}
        <p><strong>Status:</strong> {{ paper.status }}</p>
        <p>Uploaded paper: <a href="{% url 'paper:report_pdf' paper.id %}">{{ paper.name }}</a></p>

        {% if is_reviewer and paper.status == "pending" %}
            <form class="ui form" method="post" action="/paper/{{ paper.id }}/approve">
                {% csrf_token %}
                <div class="field">
                    <button class="ui primary button" type="submit">Approve</button>
                </div>
            </form>
            <form class="ui form" method="post" action="/paper/{{ paper.id }}/reject">
                {% csrf_token %}
                <div class="field">
                    <input type="text" name="comment" placeholder="Enter comment" required>
                </div>
                <button class="ui red button" type="submit">Reject</button>
            </form>
            {% endif %}
        </div>
    </body>
    </html>
    